version: '3.8'

services:
  search-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: SearchService
    ports:
      - "5008:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - spsif-library-network

  author-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: AuthorService
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - spsif-library-network

  category-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: CategoryService
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - spsif-library-network

  publisher-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: PublisherService
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - spsif-library-network

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: GatewayService
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - search-service
      - author-service
      - category-service
      - publisher-service
    networks:
      - spsif-library-network

networks:
  spsif-library-network:
    driver: bridge