-- AlterTable
ALTER TABLE "Publisher" ADD COLUMN     "bossName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "createdDated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "description" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "endDate" TIMESTAMP(3),
ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true;
