/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as AuthorsIndexRouteImport } from './routes/authors.index'
import { Route as CategoriesCreateRouteImport } from './routes/categories.create'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories.$categoryId'
import { Route as BooksCreateRouteImport } from './routes/books.create'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as AuthorsCreateRouteImport } from './routes/authors.create'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors.$authorId'
import { Route as ApiUploadthingRouteRouteImport } from './routes/api/uploadthing/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorsRoute,
} as any)
const CategoriesCreateRoute = CategoriesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CategoriesRoute,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => CategoriesRoute,
} as any)
const BooksCreateRoute = BooksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const AuthorsCreateRoute = AuthorsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthorsRoute,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/$authorId',
  path: '/$authorId',
  getParentRoute: () => AuthorsRoute,
} as any)
const ApiUploadthingRouteRoute = ApiUploadthingRouteRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/api/uploadthing': typeof ApiUploadthingRouteRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/authors/create': typeof AuthorsCreateRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/create': typeof BooksCreateRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/create': typeof CategoriesCreateRoute
  '/authors/': typeof AuthorsIndexRoute
  '/books/': typeof BooksIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/uploadthing': typeof ApiUploadthingRouteRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/authors/create': typeof AuthorsCreateRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/create': typeof BooksCreateRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/create': typeof CategoriesCreateRoute
  '/authors': typeof AuthorsIndexRoute
  '/books': typeof BooksIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/api/uploadthing': typeof ApiUploadthingRouteRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/authors/create': typeof AuthorsCreateRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/create': typeof BooksCreateRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/categories/create': typeof CategoriesCreateRoute
  '/authors/': typeof AuthorsIndexRoute
  '/books/': typeof BooksIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors'
    | '/books'
    | '/categories'
    | '/profile'
    | '/api/uploadthing'
    | '/authors/$authorId'
    | '/authors/create'
    | '/books/$bookId'
    | '/books/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/authors/'
    | '/books/'
    | '/categories/'
    | '/profile/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/uploadthing'
    | '/authors/$authorId'
    | '/authors/create'
    | '/books/$bookId'
    | '/books/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/authors'
    | '/books'
    | '/categories'
    | '/profile'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/authors'
    | '/books'
    | '/categories'
    | '/profile'
    | '/api/uploadthing'
    | '/authors/$authorId'
    | '/authors/create'
    | '/books/$bookId'
    | '/books/create'
    | '/categories/$categoryId'
    | '/categories/create'
    | '/authors/'
    | '/books/'
    | '/categories/'
    | '/profile/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRoute: typeof AuthorsRouteWithChildren
  BooksRoute: typeof BooksRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ApiUploadthingRouteRoute: typeof ApiUploadthingRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/authors/': {
      id: '/authors/'
      path: '/'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof AuthorsRoute
    }
    '/categories/create': {
      id: '/categories/create'
      path: '/create'
      fullPath: '/categories/create'
      preLoaderRoute: typeof CategoriesCreateRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/books/create': {
      id: '/books/create'
      path: '/create'
      fullPath: '/books/create'
      preLoaderRoute: typeof BooksCreateRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/authors/create': {
      id: '/authors/create'
      path: '/create'
      fullPath: '/authors/create'
      preLoaderRoute: typeof AuthorsCreateRouteImport
      parentRoute: typeof AuthorsRoute
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof AuthorsRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthorsRouteChildren {
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  AuthorsCreateRoute: typeof AuthorsCreateRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
}

const AuthorsRouteChildren: AuthorsRouteChildren = {
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  AuthorsCreateRoute: AuthorsCreateRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
}

const AuthorsRouteWithChildren =
  AuthorsRoute._addFileChildren(AuthorsRouteChildren)

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksCreateRoute: typeof BooksCreateRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksCreateRoute: BooksCreateRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface CategoriesRouteChildren {
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CategoriesCreateRoute: typeof CategoriesCreateRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CategoriesCreateRoute: CategoriesCreateRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface ProfileRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRouteWithChildren,
  BooksRoute: BooksRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ApiUploadthingRouteRoute: ApiUploadthingRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
